#!/usr/bin/perl -w



open(INFILE, "../../sysinfo.gap") or die "cannot found ../../sysinfo.gap";
close(INFILE);

sub DoClean($)
{
    my ($ThePre) = @_;
    $eMakefile=$ThePre."/Makefile";
    $fMakefile=$ThePre."/makefile";
    print "eMakefile=".$eMakefile."\n";
    print "fMakefile=".$fMakefile."\n";
    if (-e $eMakefile || -e $fMakefile)
    {
	$order="(cd ".$ThePre." && make clean)";
	print $order."\n";
	if (system($order) != 0) {
	    die "Error when doing clean\n";
	}
	#
	$eConfigure=$ThePre."/configure";
	$eMakefile=$ThePre."/makefile";
	if (-e $eConfigure && -e $eMakefile)
	{
	    $order="(cd ".$ThePre." && make distclean)";
	    print $order."\n";
	    if (system($order) != 0) {
		die "Error when doing make distclean\n";
	    }
	}
    }
}


sub DoClean_clean($)
{
    my ($ThePre) = @_;
    $eMakefile=$ThePre."/Makefile";
    $fMakefile=$ThePre."/makefile";
    print "eMakefile=".$eMakefile."\n";
    print "fMakefile=".$fMakefile."\n";
    if (-e $eMakefile || -e $fMakefile)
    {
	$order="(cd ".$ThePre." && make clean)";
	print $order."\n";
	if (system($order) != 0) {
	    die "Error when doing clean\n";
	}
	#
	$eConfigure=$ThePre."/configure";
	if (-e $eConfigure)
	{
	    $order="(cd ".$ThePre." && make clean)";
	    print $order."\n";
	    if (system($order) != 0) {
		die "Error when doing make clean\n";
	    }
	}
    }
}

DoClean("ExternalProg/export.V2.5");
print "\nCLEANED export.V2.5 (AUTO/ISOM)\n\n";

DoClean("ExternalProg/cddlib-094g_mod");
print "\nCLEANED cddlib-094g_mod\n\n";

DoClean("ExternalProg/cddlib-093b_QN");
print "\nCLEANED cddlib-093b_QN\n\n";

DoClean("ExternalProg/lrslib-042cmod");
print "\nCLEANED lrslib (gmp)\n\n";

DoClean("ExternalProg/nauty24r2");
$order="(cd ExternalProg/nauty24r2 && rm -f config.log config.status makefile && rm -f addedgeg amtog biplabg catg complg copyg countg deledgeg directg dreadnaut dreadnautB dretog genbg geng genrang labelg listg multig newedgeg NRswitchg pickg shortg showg planarg gentourng)";
print $order."\n";
if (system($order) != 0) {
    die "Error when cleaning nauty\n";
}
print "\nCLEANED nauty\n\n";
$order="(cd ExternalProg/FindNegativeVect && make clean)";
print $order."\n";
if (system($order) != 0) {
   die "Impossible to do make clean in NegativeVect\n";
}
print "\nCLEANED FindNegativeVect (find negative vector)\n\n";

DoClean("ExternalProg/SV");
print "\nCLEANED sv\n\n";

DoClean("ExternalProg/polyhedral_common");
print "\nCLEANED polyhedral_common\n\n";

