#!/usr/bin/perl -w

use Cwd;
$TheDirPWD = getcwd;

$eProg="ExternalProg/lrslib-042cmod/src-gmp/glrs";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $PrefixGMP=$TheDirPWD."/ExternalProg/gmp_install";
    $PrefixLD="LDFLAGS=\"-L".$PrefixGMP."/lib\"";
    $PrefixINC="CPPFLAGS=\"-I".$PrefixGMP."/include\"";
    $order="(cd ExternalProg/lrslib-042cmod && ./configure ".$PrefixLD." ".$PrefixINC." && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error in compilation of LRS\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED lrs (gmp)\n\n";


$order="(cd ExternalProg/Binaries && ln -sf ../lrslib-042cmod/src-gmp/glrs)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

exit 0;
