#!/usr/bin/perl -w

use Cwd;
$TheDirPWD = getcwd;

$eProg="ExternalProg/SV/src/sv";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $PrefixGMP=$TheDirPWD."/ExternalProg/gmp_install";
    $PrefixLD="LDFLAGS=\"-L".$PrefixGMP."/lib\"";
    $PrefixINC="CPPFLAGS=\"-I".$PrefixGMP."/include\"";
    $order="(cd ExternalProg/SV && ./configure ".$PrefixLD." ".$PrefixINC." && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error in compilation of SV\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED sv\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../SV/src/sv && ln -sf ../SV/src/sv_gmp_read)";
print $order."\n";
if (system($order) != 0) {
    die "Error in creating links\n";
}

exit 0;
