#!/usr/bin/perl -w

use Cwd;
$TheDirPWD = getcwd;

$eProg="ExternalProg/FindNegativeVect/src/FindNegativeVect";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $PrefixGSL=$TheDirPWD."/ExternalProg/gsl_install";
    $PrefixLD="LDFLAGS=\"-L".$PrefixGSL."/lib\"";
    $PrefixINC="CPPFLAGS=\"-I".$PrefixGSL."/include\"";
    $order="(cd ExternalProg/FindNegativeVect && ./configure ".$PrefixLD." ".$PrefixINC." && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error when compiling\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED FindNegativeVect\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../FindNegativeVect/src/FindNegativeVect)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

exit 0;
