#!/usr/bin/perl -w
$eProg1="ExternalProg/nauty24r2/dreadnaut";
$eProg2="ExternalProg/nauty24r2/amtog";
$test=0;
if (-e $eProg1 && -e $eProg2)
{$test=1;}
if ($test eq 0)
{
    $order="(cd ExternalProg/nauty24r2 && ./configure && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error when compiling\n";
    }
}
if (!(-e $eProg1) || !(-e $eProg2))
{
    print "Compilation of ".$eProg1." or ".$eProg2." failed\n";
    exit -1;
}
print "\nCOMPILED nauty\n\n";

$order="(cd ExternalProg/Binaries/ && ln -sf ../nauty24r2/amtog)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

$order="(cd ExternalProg/Binaries && ln -sf ../nauty24r2/dreadnaut)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

exit 0;
