#!/usr/bin/perl -w

use Cwd;
$TheDirPWD = getcwd;

$eProg1="ExternalProg/cdd_install_QN/bin/scdd_gmp";
$eProg2="ExternalProg/cdd_install_QN/bin/lcdd_gmp";
$eProg3="ExternalProg/cdd_install_QN/bin/testlp2_gmp";
$eProg4="ExternalProg/cdd_install_QN/bin/redcheck_gmp";
$eProg5="ExternalProg/cdd_install_QN/bin/adjacency_gmp";
$test=0;
if (-e $eProg1 && -e $eProg2 && -e $eProg3 && -e $eProg4 && -e $eProg5)
{$test=1;}
if ($test eq 0)
{
    $PrefixCDD=$TheDirPWD."/ExternalProg/cdd_install_QN";
    $PrefixGMP=$TheDirPWD."/ExternalProg/gmp_install";
    $PrefixLD="LDFLAGS=\"-L".$PrefixGMP."/lib\"";
    $PrefixINC="CPPFLAGS=\"-I".$PrefixGMP."/include\"";
    $order="(cd ExternalProg/cddlib-093b_QN && ./configure --prefix=".$PrefixCDD." ".$PrefixLD." ".$PrefixINC." && make && make install)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error when compiling\n";
    }
}
print "\nCOMPILED cddlib-093b_QN\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../cdd_install_QN/bin/lcdd_gmp lcdd_QN)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

$order="(cd ExternalProg/Binaries && ln -sf ../cdd_install_QN/bin/redcheck_gmp redcheck_QN)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

$order="(cd ExternalProg/Binaries && ln -sf ../cdd_install_QN/bin/adjacency_gmp adjacency_QN)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

$order="(cd ExternalProg/Binaries && ln -sf ../cdd_install_QN/bin/scdd_gmp scdd_QN)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

$order="(cd ExternalProg/Binaries && ln -sf ../cdd_install_QN/bin/testlp2_gmp testlp2_QN)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

exit 0;
