#!/usr/bin/perl -w

@LinesPrimal=();
@LinesDual=();
@LinesDualDir=();


$InSch=0;
$InPri=0;
$InDua=0;
$InDuaDir=0;
$GetOptimal=0;
$GetPrimal=0;
$GetDual=0;
$GetDualDir=0;
$Nval=$ARGV[0];
while (<STDIN>)
{
    s/\n//;
    $line=$_;
    $WDS=0;
    if ($line eq "begin" && $WDS eq 0)
    {
	$InSch=1;
	$WDS=1;
    }
    if ($line eq "end" && $WDS eq 0)
    {
	$InSch=0;
	$WDS=1;
    }
    if (($line eq "  primal_solution" || $line eq "  primal_direction") && $WDS eq 0 && $InSch eq 1)
    {
	$InPri=1;
	$GetPrimal=1;
	@U=split(" ", $line);
	$ChnPrimal=$U[0];
	$InDua=0;
	$InDuaDir=0;
	$WDS=1;
    }
    if ($line eq "  dual_solution" && $WDS eq 0 && $InSch eq 1)
    {
	$InPri=0;
	$InDua=1;
	$InDuaDir=0;
	$GetDual=1;
	$WDS=1;
    }
    if ($line eq "  dual_direction" && $WDS eq 0 && $InSch eq 1)
    {
	$InPri=0;
	$InDua=0;
	$InDuaDir=1;
	$GetDualDir=1;
	$WDS=1;
    }
    @S=split(" ", $line);
    if (scalar(@S)>0 && $S[0] eq "optimal_value" && $WDS eq 0  && $InSch eq 1)
    {
	$InPri=0;
	$InDua=0;
	$InDuaDir=0;
	$optival1=$S[2];
	$optival2=$S[3];
	$GetOptimal=1;
	$WDS=1;
    }
    if ($InPri eq 1 && $WDS eq 0 && $InSch eq 1)
    {
	$LinesPrimal[scalar(@LinesPrimal)]=$line;
    }
    if ($InDua eq 1 && $WDS eq 0 && $InSch eq 1)
    {
	$LinesDual[scalar(@LinesDual)]=$line;
    }
    if ($InDuaDir eq 1 && $WDS eq 0 && $InSch eq 1)
    {
	$LinesDualDir[scalar(@LinesDualDir)]=$line;
    }
}
$first=1;

sub TheQNstr($$)
{
    my ($val1, $val2) = @_;
    $MyRet=$val1."+Sqrt(".$Nval.")*".$val2;
    return $MyRet;
}

print "return rec(";
if ($GetPrimal eq 1)
{
    if ($first eq 0)
    {
	print ", ";
    }
    $first=0;
    print $ChnPrimal.":=[";
    for ($iLine=1; $iLine<=scalar(@LinesPrimal); $iLine++)
    {
	@S=split(" ", $LinesPrimal[$iLine-1]);
	print "[".$S[0].",".TheQNstr($S[2], $S[3])."]";
	if ($iLine < scalar(@LinesPrimal))
	{
	    print ", ";
	}
    }
    print "]";
}
if ($GetDual eq 1)
{
    if ($first eq 0)
    {
	print ", ";
    }
    $first=0;
    print "dual_solution:=[";
    for ($iLine=1; $iLine<=scalar(@LinesDual); $iLine++)
    {
	@S=split(" ", $LinesDual[$iLine-1]);
	print "[".$S[0].",".TheQNstr($S[2], $S[3])."]";
	if ($iLine < scalar(@LinesDual))
	{
	    print ", ";
	}
    }
    print "]";
}
if ($GetDualDir eq 1)
{
    if ($first eq 0)
    {
	print ", ";
    }
    $first=0;
    print "dual_direction:=[";
    for ($iLine=1; $iLine<=scalar(@LinesDualDir); $iLine++)
    {
	@S=split(" ", $LinesDualDir[$iLine-1]);
	print "[".$S[0].",".TheQNstr($S[2], $S[3])."]";
	if ($iLine < scalar(@LinesDualDir))
	{
	    print ", ";
	}
    }
    print "]";
}
if ($GetOptimal eq 1)
{
    if ($first eq 0)
    {
	print ", ";
    }
    $first=0;
#    print "optimal: optival=".$optival."\n";
    print "optimal:=".TheQNstr($optival1, $optival2);
}
print ");\n";
