#!/usr/bin/perl -w

$File=$ARGV[0];

open(INFILE, $File);
@RESUL=<INFILE>;
close(INFILE);

$lastline=$RESUL[scalar(@RESUL)-1];
if ($lastline eq "h and h' are different.\n")
{
    print "return false;\n";
}
else
{
    $idx=1;
    while(1)
    {
	if ($RESUL[$idx-1] eq "h and h' are identical.\n")
	{
	    last;
	}
	$idx++;
    }
    $idx++;
    @MAPPING=();
    $nbVert=0;
    for ($iLine=$idx; $iLine<=scalar(@RESUL); $iLine++)
    {
	@VEL=split(" ", $RESUL[$iLine-1]);
	for ($iME=1; $iME<=scalar(@VEL); $iME++)
	{
	    @SLK=split("-", $VEL[$iME-1]);
	    $MAPPING[$SLK[0]]=$SLK[1];
	    $val=$SLK[0]+1;
	    if ($val>$nbVert)
	    {
		$nbVert=$val;
	    }
	}
    }
    print "return [";
    for ($iVert=1; $iVert<=$nbVert; $iVert++)
    {
	$val=$MAPPING[$iVert-1]+1;
	print $val;
	if ($iVert< $nbVert)
	{
	    print ",";
	}
    }
    print "];\n";
}
