#!/usr/bin/perl -w

$Nval=$ARGV[0];
$eFile=$ARGV[1];
$Nsqr=sqrt($Nval);

open(INFILE, $eFile);
@RESULT=<INFILE>;
close(INFILE);

sub GetReal($)
{
    my ($str1) = @_;
    $_=$str1;
    s/\n//;
    $esl=$_;
    @VV=split("/", $esl);
    if (scalar(@VV) eq 2)
    {
	$fre=$VV[0]/$VV[1];
	return $fre;
    }
    else
    {
	return $esl;
    }
}

sub GetDoubleFromPair($$)
{
    my ($str1, $str2) = @_;
    $val1=GetReal($str1);
    $val2=GetReal($str2);
    $MyRet=$val1+$Nsqr*$val2;
    return $MyRet;
}



for ($iLine=1; $iLine<=scalar(@RESULT); $iLine++)
{
    $eLine=$RESULT[$iLine-1];
    @UU=split(" ", $eLine);
    $nb=scalar(@UU);
    $quot=int($nb/2);
    $res=$nb-$quot*2;
    if ($res == 1)
    {
	print $eLine;
    }
    else
    {
	$nb2=$nb/2;
	for ($iCol=1; $iCol<=$nb2; $iCol++)
	{
	    $idx1=2*($iCol-1);
	    $idx2=2*($iCol-1)+1;
	    $str1=$UU[$idx1];
	    $str2=$UU[$idx2];
	    $doubl=GetDoubleFromPair($str1, $str2);
	    print " ".$doubl;
	}
	print "\n";
    }
}
